server:
  port: 8080

spring:
  application:
    name: blog-service
  # Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:

  # H2
  h2:
    console:
      enabled: true
      path: /h2_console
  # JPA
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
    open-in-view: false

logging:
  file: logs/blog_service_app.log
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: INFO
    com.jeonguk.web: INFO
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

# Feign config : Test echo server call
echo:
  api:
    server:
      url: http://localhost:8088/